const mongoose = require('mongoose');

const { Schema } = mongoose;

/**
 * Supported planner entry views used for user preference defaults.
 * @readonly
 * @enum {string}
 */
const DEFAULT_VIEWS = Object.freeze({
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY'
});

/**
 * User account schema with nested UX preferences used to personalize planner
 * behavior and rendering defaults.
 *
 * @typedef {Object} User
 * @property {string} name - Display name.
 * @property {string} email - Unique account identifier.
 * @property {string} passwordHash - Argon2/bcrypt hash generated by auth layer.
 * @property {boolean} isActive - Indicates account activity state.
 * @property {Date} lastLoginAt - Last successful authentication timestamp.
 * @property {{ timezone: string, defaultView: 'DAILY'|'WEEKLY'|'MONTHLY' }} preferences
 */
const userSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
      minlength: 2,
      maxlength: 120
    },
    email: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      lowercase: true,
      maxlength: 320,
      index: true
    },
    passwordHash: {
      type: String,
      required: true,
      minlength: 20
    },
    isActive: {
      type: Boolean,
      default: true,
      index: true
    },
    lastLoginAt: {
      type: Date,
      default: null
    },
    preferences: {
      timezone: {
        type: String,
        default: 'UTC',
        trim: true,
        maxlength: 100
      },
      defaultView: {
        type: String,
        enum: Object.values(DEFAULT_VIEWS),
        default: DEFAULT_VIEWS.WEEKLY
      }
    }
  },
  {
    timestamps: true,
    versionKey: false
  }
);

userSchema.index({ email: 1 }, { unique: true });

userSchema.pre('save', function normalizeEmailAndTimezone(next) {
  if (this.email) {
    this.email = this.email.toLowerCase().trim();
  }

  if (this.preferences?.timezone) {
    this.preferences.timezone = this.preferences.timezone.trim();
  }

  return next();
});

const User = mongoose.model('User', userSchema);

module.exports = {
  User,
  DEFAULT_VIEWS
};
